import { readFileSync, writeFileSync } from "node:fs";

// Builds packages/pipeline/src/enrich/usPlaces.generated.ts from the US Census Bureau Gazetteer "places" file
// (public domain): https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2024_Gazetteer/2024_Gaz_place_national.zip
// Run: tsx scripts/build-us-places.ts <path to the unzipped 2024_Gaz_place_national.txt>
// One line per place: "name|ST|lat|lon", name lowercased with the Census legal-area suffix (city, town, CDP...) removed.
const SUFFIX = /\s+(city and borough|consolidated government|metropolitan government|unified government|urban county|city|town|village|borough|municipality|township|cdp|comunidad|zona urbana|plantation|corporation)(\s*\(balance\))?$/i;
export const placeName = (n: string) => n.replace(SUFFIX, "").replace(/\s*\(.*\)$/, "").toLowerCase().replace(/\./g, "").replace(/^st /, "saint ").trim();

const [, , src] = process.argv;
const lines = readFileSync(src, "latin1").split("\n").slice(1).filter(Boolean);
const best = new Map<string, { land: number; row: string }>(); // same name in one state: keep the largest place
for (const line of lines) {
  const c = line.split("\t").map((x) => x.trim());
  const [usps, , , name, , , aland] = c;
  const lat = Number(c[10]), lon = Number(c[11]);
  if (!usps || !name || Number.isNaN(lat) || Number.isNaN(lon)) continue;
  const key = `${placeName(name)}|${usps}`;
  const land = Number(aland);
  if (!best.has(key) || land > best.get(key)!.land) best.set(key, { land, row: `${key}|${lat.toFixed(3)}|${lon.toFixed(3)}` });
}
const body = [...best.values()].map((v) => v.row).sort().join("\n");
writeFileSync(
  "packages/pipeline/src/enrich/usPlaces.generated.ts",
  `// GENERATED by scripts/build-us-places.ts. Do not edit.\n// Source: US Census Bureau 2024 Gazetteer, places (public domain). ${best.size} places, "name|ST|lat|lon".\nexport const US_PLACES = \`${body}\`;\n`,
);
console.log(`wrote ${best.size} places`);
